Добавлена разметка hero
NaTaLiaMoSKV/ice-cream pull request #2
Opened 2022-10-07 17:38 UTC by m-boiko

Добавлена разметка hero

2022-10-07 18:09 UTC, NaTaLiaMoSKV requested changes

2022-10-07 18:09 UTC, NaTaLiaMoSKV commented on src/partials/hero.html
> +        <a class="anchor-list__link" href="">Products</a>
Нужно добавить href="#products" для тега а

2022-10-07 18:09 UTC, NaTaLiaMoSKV commented on src/partials/hero.html
> +        <a class="anchor-list__link" href="">How it’s made?</a>
Нужно добавить href="#about" для тега а

2022-10-08 03:42 UTC, m-boiko commented on src/partials/hero.html
> +        <a class="anchor-list__link" href="">Products</a>
Добавил

2022-10-08 03:42 UTC, m-boiko commented on src/partials/hero.html
> +        <a class="anchor-list__link" href="">How it’s made?</a>
Добавил

2022-10-08 07:16 UTC, NaTaLiaMoSKV approved these changes

2022-10-08 07:17 UTC, merged