adds modal-hero
NaTaLiaMoSKV/ice-cream pull request #7
Opened 2022-10-08 13:48 UTC by Sebastyann

Привіт, поки що перше модельне  вікно hero без малюнків.

2022-10-08 19:11 UTC, NaTaLiaMoSKV requested changes
Привет) Пока что нужно изменить названия классов в html, scss еще не нужен.

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +<div class="backdrop is-hidden">
Нужно добавить 
`<div hero-modal class="backdrop is-hidden">`
для скрипта

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +    <button type="button" class="modal-close-btn">
`<button type="button" hero-modal-close class="modal-close-btn">`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +      <div class="modal-hero-item">
Отпиши в лс для чего нужен этот див

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +        <ul class="modal-hero-list">
`class="modal-hero-form__list"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +          <li class="modal-hero__ice-cream">
`class="modal-hero-form__ice-cream"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__circle-green"></div>
`class="modal-hero-form__circle--green"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--green"></div>
`class="modal-hero-form__img--green"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--green"></div>
`class="modal-hero-form__img--green"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +          <li class="modal-hero__ice-coffee">
`class="modal-hero-form__ice-coffee"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__circle-yellov"></div>
`class="modal-hero-form__circle--yellow"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--yellov"></div>
`class="modal-hero-form__img--yellow"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +          <li class="modal-hero__ice-milkshakes">
`class="modal-hero-form__ice-milkshake"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__circle-red"></div>
`class="modal-hero-form__circle--red"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--red"></div>
`class="modal-hero__img--red"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +      <label class="modal-form-field">
`"modal-hero-form__label"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +        <span class="modal-form-input-wrapper">
`class="modal-hero-form__wrapper"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            class="modal-hero-input"
`class="modal-hero-form__input"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +      <label class="modal-form-field">
`class="modal-hero-form__label"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +        <span class="modal-form-input-wrapper">
`class="modal-hero-form__wrapper"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            class="modal-hero-input"
`class="modal-hero-form__input"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +      <label class="modal-form-field">
`class="modal-hero-form__label"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +          class="modal-hero-input__textarea"
`class="modal-hero-form__textarea"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +      <button type="submit" class="button-modal-hero">Submit</button>
`class="modal-hero-form__button"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +<!-- <div class="backdrop is-hidden">
`<div products-modal class="backdrop is-hidden">`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +    <button type="button" class="modal-close-btn">
`<button type="button" products-modal-close class="modal-close-btn">`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +      <div class="modal-hero-item"></div>
Не совсем понимаю значение этого дива. Если он для ингридиентов, то лучше подоужет название класса `modal-products-form__ingridients`, а если для списка состава продукта, то можно `modal-products-form__nutritional-value`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +      <label class="modal-form-field">
`class="modal-hero-form__label"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +        <span class="modal-form-input-wrapper">
`class="modal-hero-form__wrapper"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +            class="modal-hero-input"
` class="modal-hero-form__input"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +      <label class="modal-form-field">
`class="modal-hero-form__label"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +        <span class="modal-form-input-wrapper">
`class="modal-hero-form__wrapper"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +            class="modal-hero-input"
` class="modal-hero-form__input"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +            placeholder="Fhone"
Опечатка с слове Phone

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            placeholder="Fhone"
Опечатка в слове Phone

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +      <label class="modal-form-field">
`modal-hero-form__label`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +          class="modal-hero-input__textarea"
`class="modal-hero-form__textarea"`

2022-10-08 19:11 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +      <button type="submit" class="button-modal-hero">Submit</button>
`class="modal-hero-form__button"`
Кстати, классы на кнопки пока не окончательные, так как они будут стилизовать другим человеком, и уже он выберет общий класс для всех.

2022-10-08 19:37 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +        <ul class="modal-hero-list">
Не обратила сразу внимание. в 9 строчке лучше добавить `class="modal-hero-form__title"` (и во второй модалке тоже), чтобы сохранить единый стиль

2022-10-08 19:54 UTC, Sebastyann commented on src/partials/hero-modal.html
> +<div class="backdrop is-hidden">
![бекдроп - хіро](https://user-images.githubusercontent.com/109735124/194725662-74b76a8f-6503-4575-ab7a-eee56b489e52.jpg)

2022-10-08 19:56 UTC, Sebastyann commented on src/partials/hero-modal.html
> +<div class="backdrop is-hidden">
Зробив

2022-10-08 19:57 UTC, Sebastyann commented on src/partials/hero-modal.html
> +    <button type="button" class="modal-close-btn">
Готово :)

2022-10-08 20:03 UTC, Sebastyann commented on src/partials/hero-modal.html
> +      <div class="modal-hero-item">
.modal-hero-item {
  margin-bottom: 40px;
} 
![Screenshot_12](https://user-images.githubusercontent.com/109735124/194725959-77180bed-9e0f-4ae4-a13f-6118d4668f7c.jpg)

2022-10-08 20:04 UTC, Sebastyann commented on src/partials/hero-modal.html
> +      <div class="modal-hero-item">
хоча думаю можна прибрати а з іншого місця відштовхнути.

2022-10-08 20:08 UTC, Sebastyann commented on src/partials/hero-modal.html
> +        <ul class="modal-hero-list">
Добре, дякую.

2022-10-08 20:11 UTC, Sebastyann commented on src/partials/hero-modal.html
> +          <li class="modal-hero__ice-cream">
якщо у 12 рядку. так, змінюю.

2022-10-08 20:13 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero__circle-green"></div>
Готово.

2022-10-08 20:15 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--green"></div>
Gud)

2022-10-08 20:16 UTC, Sebastyann commented on src/partials/hero-modal.html
> +          <li class="modal-hero__ice-coffee">
Готово

2022-10-08 20:18 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero__circle-yellov"></div>
Готово)

2022-10-08 20:19 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--yellov"></div>
Готово

2022-10-08 20:20 UTC, Sebastyann commented on src/partials/hero-modal.html
> +          <li class="modal-hero__ice-milkshakes">
Готово

2022-10-08 20:21 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero__circle-red"></div>
Готово

2022-10-08 20:24 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--red"></div>
не розумію що міняти, якщо це запитання, то це майбутній малюнок всередині.

2022-10-08 20:27 UTC, Sebastyann commented on src/partials/hero-modal.html
> +      <label class="modal-form-field">
замінив

2022-10-08 20:29 UTC, Sebastyann commented on src/partials/hero-modal.html
> +        <span class="modal-form-input-wrapper">
готово

2022-10-08 20:30 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            class="modal-hero-input"
Готово

2022-10-08 20:33 UTC, Sebastyann commented on src/partials/hero-modal.html
> +          class="modal-hero-input__textarea"
Готово

2022-10-08 20:34 UTC, Sebastyann commented on src/partials/hero-modal.html
> +      <button type="submit" class="button-modal-hero">Submit</button>
Готово

2022-10-08 20:35 UTC, Sebastyann commented on src/partials/products-modal.html
> +<!-- <div class="backdrop is-hidden">
Готово

2022-10-08 20:36 UTC, Sebastyann commented on src/partials/products-modal.html
> +    <button type="button" class="modal-close-btn">
Готово

2022-10-08 20:41 UTC, Sebastyann commented on src/partials/products-modal.html
> +      <div class="modal-hero-item"></div>
.modal-hero-item {
  margin-bottom: 40px;   був просисав

2022-10-08 20:42 UTC, Sebastyann commented on src/partials/products-modal.html
> +            placeholder="Fhone"
Готово, дякую.

2022-10-09 08:34 UTC, NaTaLiaMoSKV requested changes
Поправки по html сделала. Отправь, пожалуйста, готовый вариант, и я приступлю к проверке scss

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +      <div class="modal-hero-item">
Если тебе нужен, то оставляй. Но вообще можно сделать margin-bottom от списка, коорый сейчас внутри этого дива.

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +        <ul class="modal-hero-list">
Не вижу изменений в этой строчке. Ты их не сделал или у меня не отображается?

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero-form__img--yellov"></div>
Опечатка в слове yellow

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero__img--red"></div>
Да, прости. Я случайно закинула не в эту строчку. в 23 строке поставь, пожалуйста, `class="modal-hero-form__circle--red"` с двумя тире перед red согласно методологии ВЕМ

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/hero-modal.html
> +            <div class="modal-hero-form__circle-yellov"></div>
Опечатка в слове yellow. По методологиии ВЕМ перед  yellow нужно два тире

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +    <button type="button" products-modal-close class="modal-close-btn">
`product-modal-open` У меня была проблема со скриптом, поэтому пришлось поменять название дополнительного класса.

2022-10-09 08:34 UTC, NaTaLiaMoSKV commented on src/partials/products-modal.html
> +<!-- <div products-modal class="backdrop is-hidden">
здесь тоже нужно поменять на `product-modal` , так как в скрипте уже другое значение

2022-10-09 09:49 UTC, Sebastyann commented on src/partials/hero-modal.html
> +            <div class="modal-hero-form__img--yellov"></div>
Дякую, погане в мене знання Інглиша))

2022-10-09 09:53 UTC, Sebastyann commented on src/partials/products-modal.html
> +    <button type="button" products-modal-close class="modal-close-btn">
Добре, заміню на product-modal-open

2022-10-09 09:54 UTC, Sebastyann commented on src/partials/products-modal.html
> +<!-- <div products-modal class="backdrop is-hidden">
Добре, поміняв

2022-10-10 08:18 UTC, NaTaLiaMoSKV approved these changes

2022-10-10 09:32 UTC, merged