franchise-modal
NaTaLiaMoSKV/ice-cream pull request #8
Opened 2022-10-08 16:11 UTC by Khrystyna-Harasym

створено окрім розмітки , стилізацію модального вікна. js script не підключала , тому i is-hidden backdrop не додавала. тимчасово додала стилі до кнопки Submit, а також outline до input і  textarea

2022-10-08 19:49 UTC, NaTaLiaMoSKV requested changes
Я скинула, какие поправки нужно сделать. scss пока что не смотрю

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +<div class="franchise-modal__backdrop " data-modal>
`<div class="backdrop is-hidden" franchise-modal>`
Тут нужно добавить дополнительный класс для скрипта

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +    <button class="franchise-modal__close-btn" type="button" data-modal-close>
`<button class="modal-close-btn" type="button" franchise-modal-close>`
в папке components лежит стиль для кнопки модального окна

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +      <svg class="franchise-modal__close-icon" width="20px" height="20px">
`class="modal-close-btn__icon"`
ширина в html указывается без пикселей

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +    <b class="franchise-modal__subtitle"
Тут нужен тег p, а в классе лучше поменять subtitle на просто title для сохранения единого стиля у всех модалок

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +    <form class="franchise-modal__form">
тег form является отдельным ВЕМ-элементом. 
`class="franchise-modal-form"`

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +        class="franchise-modal__input"
`class="franchise-modal-form__input"`

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +        class="franchise-modal__input"
`class="franchise-modal-form__input"`

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +        class="franchise-modal__input"
`class="franchise-modal-form__input"`

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +      class="frachise-modal__message"
`class="franchise-modal-form__textarea"`

2022-10-08 19:49 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +      <button class="frachise-modal__submit-btn" type="submit">Submit</button>
По методологии бема лучше добавить кнопке `class="frachise-modal-form__button"` , но так как в будущем у нас будет один общий класс для всех кнопок такого типа, то этот класс пока что временный

2022-10-08 21:25 UTC, Khrystyna-Harasym commented on src/partials/franchise-modal.html
> +<div class="franchise-modal__backdrop " data-modal>
повністю видалила клас  franchise-modal__backdrop на бекдроп  і залишила class="backdrop" , так як він окремо є в components

2022-10-08 21:25 UTC, Khrystyna-Harasym commented on src/partials/franchise-modal.html
> +    <button class="franchise-modal__close-btn" type="button" data-modal-close>
виправила

2022-10-08 21:26 UTC, Khrystyna-Harasym commented on src/partials/franchise-modal.html
> +      <svg class="franchise-modal__close-icon" width="20px" height="20px">
виправлено

2022-10-09 08:21 UTC, NaTaLiaMoSKV requested changes
Исправь, пожалуйста, html. scss не отображается у меня почему-то. Проверь его еще раз, и если у тебя там стили видно, то тогда присылай.

2022-10-09 08:21 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +    <p class="title"
`<p class="franchise-modal__title">`

2022-10-09 08:21 UTC, NaTaLiaMoSKV commented on src/partials/franchise-modal.html
> +  <div class="franchise-modal">
Тут нужно исправить класс на` "franchise-modal__container"`, чтобы имена классов не кофликтовали

2022-10-09 13:09 UTC, NaTaLiaMoSKV approved these changes

2022-10-09 13:11 UTC, merged